version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pg-agroshare
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: agroshare
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rd-agroshare
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
